steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/microservices-academy/images-hadyi/client-gateway',
        '-f',
        'Dockerfile.prod',
        '--platform=linux/amd64',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/microservices-academy/images-hadyi/client-gateway',
      ]

options:
  logging: CLOUD_LOGGING_ONLY
